#!/usr/bin/perl -w
print "Running Condor status on : @ARGV \n";

#!system ("condor_status @ARGV -l | grep Opsys") or die "Couldn't run condor_status command.";
$var = ` condor_status @ARGV -l | grep -E "^OpSys" `; 

print "Output: \n $var";

exit 0;

