#!/usr/bin/env ruby

require 'Newick'
require 'optparse'

@label = false
@highlights = nil

ARGV.options {|opts|
  opts.banner << " tree-file [..tree-file]"
  opts.on("-h", "--highlights ", String,
	  "highlight these ids (commas)") {|@highlights|}    
  opts.on("-l", "--label", "add label to tree pdf") {|@label|}    
  begin
    opts.parse!
  rescue
    STDERR.puts $!.message
    STDERR.puts opts
    exit(1)
  end
  if (ARGV.size < 1)
    STDERR.puts opts
    exit(1)
  end
}


highlights = []
if (@highlights)
  highlights = @highlights.split(",")
end

ARGV.each {|arg|
  tree = NewickTree.fromFile(arg)
  tree.draw(arg + ".pdf", "width", giLink = true, @label, highlights)
}
